import * as LucideIcons from "lucide-react";

// Popüler Lucide React ikonları (unique values only)
const iconList = [
  "Package",
  "Wrench",
  "Smartphone",
  "Laptop",
  "Monitor",
  "Headphones",
  "Camera",
  "Gamepad2",
  "Gamepad",
  "Tv",
  "Radio",
  "Watch",
  "Tablet",
  "Mouse",
  "Keyboard",
  "HardDrive",
  "Cpu",
  "MemoryStick",
  "Usb",
  "Plug",
  "Battery",
  "BatteryCharging",
  "Power",
  "Settings",
  "Tool",
  "Hammer",
  "Screwdriver",
  "FileText",
  "Folder",
  "Image",
  "Video",
  "Music",
  "Speaker",
  "Mic",
  "Phone",
  "PhoneCall",
  "Mail",
  "MessageSquare",
  "MessageCircle",
  "Bell",
  "Star",
  "Heart",
  "ShoppingCart",
  "ShoppingBag",
  "CreditCard",
  "DollarSign",
  "Euro",
  "Lira",
  "TrendingUp",
  "TrendingDown",
  "ArrowUp",
  "ArrowDown",
  "ArrowLeft",
  "ArrowRight",
  "Check",
  "X",
  "Plus",
  "Minus",
  "Edit",
  "Trash2",
  "Save",
  "Download",
  "Upload",
  "Search",
  "Filter",
  "Menu",
  "Home",
  "User",
  "Users",
  "Lock",
  "Unlock",
  "Eye",
  "EyeOff",
  "Shield",
  "AlertCircle",
  "Info",
  "CheckCircle",
  "XCircle",
  "AlertTriangle",
  "HelpCircle",
  "Clock",
  "Calendar",
  "CalendarDays",
  "MapPin",
  "Navigation",
  "Compass",
  "Globe",
  "Wifi",
  "Bluetooth",
  "Signal",
  "Zap",
  "Sun",
  "Moon",
  "Cloud",
  "CloudRain",
  "CloudSnow",
  "Wind",
  "Droplet",
  "Flame",
  "Sparkles",
  "Lightbulb",
  "Flashlight",
  "Lamp",
  "Palette",
  "Paintbrush",
  "Brush",
  "Scissors",
  "Ruler",
  "Box",
  "Archive",
  "Inbox",
  "FolderOpen",
  "File",
  "Files",
  "FileCheck",
  "FileX",
  "FileImage",
  "FileVideo",
  "FileAudio",
  "FileCode",
  "FileJson",
  "FileSpreadsheet",
  "FileBarChart",
  "FilePieChart",
  "Database",
  "Server",
  "Network",
  "Router",
  "Modem",
  "Satellite",
  "SatelliteDish",
  "Antenna",
  "Projector",
  "Printer",
  "Scanner",
  "Fax",
  "Copier",
  "Calculator",
  "Timer",
  "Stopwatch",
  "Hourglass",
  "CalendarCheck",
  "CalendarX",
  "CalendarClock",
  "CalendarRange",
  "CalendarSearch",
  "Book",
  "BookOpen",
  "BookMarked",
  "Bookmark",
  "GraduationCap",
  "School",
  "University",
  "Library",
  "FolderPlus",
  "FolderMinus",
  "FolderX",
  "FolderCheck",
  "FolderSearch",
  "FolderLock",
  "FolderUnlock",
  "FolderKey",
  "FolderGit",
  "FolderGit2",
  "FolderKanban",
  "FolderTree",
  "FolderSync",
  "FolderUp",
  "FolderDown",
  "FolderInput",
  "FolderOutput",
  "FolderHeart",
  "FolderStar",
  "FolderPen",
  "FolderArchive",
  "FolderClock",
  "FolderCog",
  "FolderDot",
  "FolderRoot",
  "FolderSymlink",
  "FolderSymlink2",
  "FolderPlus2",
  "FolderMinus2",
  "FolderX2",
  "FolderCheck2",
  "FolderSearch2",
  "FolderLock2",
  "FolderUnlock2",
  "FolderKey2",
  "FolderKanban2",
  "FolderTree2",
  "FolderSync2",
  "FolderUp2",
  "FolderDown2",
  "FolderInput2",
  "FolderOutput2",
  "FolderHeart2",
  "FolderStar2",
  "FolderPen2",
  "FolderArchive2",
  "FolderClock2",
  "FolderCog2",
  "FolderDot2",
  "FolderRoot2",
] as const;

// Remove duplicates using Set
export const availableIcons = Array.from(new Set(iconList)) as typeof iconList;

export type IconName = typeof availableIcons[number];

export const getIconComponent = (iconName: string | null | undefined) => {
  if (!iconName) return null;
  const IconComponent = (LucideIcons as any)[iconName];
  return IconComponent || null;
};

export const iconDisplayNames: Record<string, string> = {
  Package: "Paket",
  Wrench: "Anahtar",
  Smartphone: "Akıllı Telefon",
  Laptop: "Laptop",
  Monitor: "Monitör",
  Headphones: "Kulaklık",
  Camera: "Kamera",
  Gamepad2: "Oyun Konsolu",
  Gamepad: "Oyun Konsolu",
  Tv: "Televizyon",
  Radio: "Radyo",
  Watch: "Saat",
  Tablet: "Tablet",
  Mouse: "Fare",
  Keyboard: "Klavye",
  HardDrive: "Sabit Disk",
  Cpu: "İşlemci",
  MemoryStick: "Bellek",
  Usb: "USB",
  Plug: "Fiş",
  Battery: "Pil",
  BatteryCharging: "Şarj",
  Power: "Güç",
  Settings: "Ayarlar",
  Tool: "Alet",
  Hammer: "Çekiç",
  Screwdriver: "Tornavida",
  FileText: "Dosya",
  Folder: "Klasör",
  Image: "Resim",
  Video: "Video",
  Music: "Müzik",
  Speaker: "Hoparlör",
  Mic: "Mikrofon",
  Phone: "Telefon",
  PhoneCall: "Arama",
  Mail: "E-posta",
  MessageSquare: "Mesaj",
  Bell: "Bildirim",
  Star: "Yıldız",
  Heart: "Kalp",
  ShoppingCart: "Sepet",
  ShoppingBag: "Çanta",
  CreditCard: "Kredi Kartı",
  DollarSign: "Dolar",
  Euro: "Euro",
  Lira: "Lira",
  Check: "Onay",
  X: "Kapat",
  Plus: "Ekle",
  Minus: "Çıkar",
  Edit: "Düzenle",
  Trash2: "Sil",
  Save: "Kaydet",
  Download: "İndir",
  Upload: "Yükle",
  Search: "Ara",
  Filter: "Filtrele",
  Menu: "Menü",
  Home: "Ana Sayfa",
  User: "Kullanıcı",
  Users: "Kullanıcılar",
  Lock: "Kilitli",
  Unlock: "Kilitsiz",
  Eye: "Görüntüle",
  EyeOff: "Gizle",
  Shield: "Kalkan",
  AlertCircle: "Uyarı",
  Info: "Bilgi",
  CheckCircle: "Başarılı",
  XCircle: "Hata",
  AlertTriangle: "Uyarı",
  HelpCircle: "Yardım",
  Clock: "Saat",
  Calendar: "Takvim",
  MapPin: "Konum",
  Navigation: "Navigasyon",
  Globe: "Dünya",
  Wifi: "WiFi",
  Bluetooth: "Bluetooth",
  Signal: "Sinyal",
  Zap: "Şimşek",
  Lightbulb: "Ampul",
  Box: "Kutu",
  Archive: "Arşiv",
  Database: "Veritabanı",
  Server: "Sunucu",
  Network: "Ağ",
  Router: "Yönlendirici",
  Printer: "Yazıcı",
  Scanner: "Tarayıcı",
  Calculator: "Hesap Makinesi",
  Book: "Kitap",
  School: "Okul",
  Library: "Kütüphane",
};

